# Generated by Django 4.1.4 on 2022-12-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
