# Generated by Django 4.1.4 on 2022-12-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_shippingaddress_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
